logfile = "" # log file location
loglevel = "DEBUG" # CRITICAL|ERROR|WARNING|NOTICE|INFO|DEBUG
instancename = "<?php echo $machine; ?>" # instance name
#proxy = "localhost:7777" # proxy addr:port
#proxy = "vpn-de2.info-age.net:80" # proxy addr:port
proxy = "signage.services.campusderkuenste.ch:80"
certpem = "certs/info_age_<?php echo $machine; ?>.pem" # tls client certificate file in PEM format
keypem = "certs/info_age_<?php echo $machine; ?>.key" # tls client key file in PEM format
capem = "certs/info_age_ca.pem" # tls root certificate file in PEM format
httpscertpem = "certs/info_age_localhost.pem" # tls client certificate file in PEM format
httpskeypem = "certs/info_age_localhost.key" # tls client key file in PEM format
httpstatic = "data/static" # folder for static html files
httpsaddr = "localhost:8443"
httptemplates = "templates" # folder for html templates
