<?php
  include( '../init.inc.php' );

  function escapeLatex( $str ) {
    return preg_replace(
      array(
          '/~/',
          '/\^/',
          "/\\\\/",
          '/([&%$#_\{}])/',
      ),
      array(
          '\\\\textasciitilde',
          '\\\\textasciicircum',
          '\\\\textbackslash',
          '\\\\\1',
        ),
      $str
    );
  }

?>\documentclass[a4paper]{book}
\usepackage[utf8]{inputenc}
\usepackage{graphicx}
\usepackage{fancyhdr}
\usepackage{layout}
\inputencoding{utf8}
\pagestyle{fancy}
\marginparwidth=0pt
\fancyhf{}
\rhead{Institute for Visual Communication}
\lhead{Peter von Arx}
\rfoot{Page \thepage}
\lfoot{generated by Center for Digital Matter}
\title{Peter von Arx Archive}
\author{Insitute Visual Communication}
\date{\today}
\begin{document}
   \maketitle
   \newpage
<?php
$sql = "SELECT * FROM source_vonarx_box1 ORDER BY ObjectNr ASC";
$rs = $db->Execute( $sql );
if( true ) foreach( $rs as $row ) {
  $objnr = $row['ObjectNr'];
  $sql = "SELECT * FROM mediaserver.master WHERE signature = ".$db->qstr( $objnr );
  $imgrow = $db->GetRow( $sql );
  if( !$imgrow ) continue;
  $image = substr( $imgrow['urn'], 26 );
  $file = pathinfo( $image, PATHINFO_BASENAME );
  $tmpfile = '/nfsdata/tmp/tmp.jpg';
  $newfile = '/nfsdata/tmp/'.str_replace( '.', '_', $file ).'.jpg';
  $cmd = 'convert '.escapeshellarg( $image ).' -resize 1920x1920 '.escapeshellarg( $tmpfile );
//  echo "{$cmd}\n";
  if( !file_exists( $newfile )) {
    @unlink( $tmpfile );
    exec( $cmd );
    rename( $tmpfile, $newfile );
  }
?>
  \section*{<?php echo escapeLatex( $row['Title'] ); ?>}
  \begin{center}
  \includegraphics[width=10cm, height=9cm, keepaspectratio=true]{<?=$newfile ?>}
  \end{center}
  \begin{tabular}{ r l }
<?php
  $first = true;
  foreach( $row as $k=>$v ) {
    if( strlen( trim( $v )) == 0 ) continue;
    if( !$first ) echo "  \\\\\n";
    if( $first ) $first = false;
    echo '      \textbf{'.escapeLatex($k).'} & '.escapeLatex($v);
    //break;
  }
  echo "\n";
?>
  \end{tabular}
  \newpage
<?php
}
$rs->Close();
?>
\end{document}
