<?php

$fullcachewithurl = array(
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_birne.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_bluse.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_bohrer.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_bueffel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_buerste.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_dackel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_ente.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_erbse.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_esel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_eule.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_fenchel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_gabel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_glocke.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_gurke.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_hammer.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_hamster.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_hocker.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_jacke.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_joghurt.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_kaefer.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_kaktus.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_kirsche.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_kiste.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_kiwi.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_knoblauch.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_lama.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_locher.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_loeffel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_mantel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_moewe.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_muecke.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_muschel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_nadel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_palme.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_pfirsich.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_pflaster.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_pudel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_ratte.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_rose.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_ruder.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_saege.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_sauce.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_schaufel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_schinken.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_schlitten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_schraube.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_seife.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_sessel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_sofa.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_spargel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_spinne.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_spritze.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_stiefel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_suppe.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_tanne.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_tasse.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_tiger.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_torte.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_trichter.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_tulpe.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_vase.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_wecker.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_wespe.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_wuerfel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_zebra.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_zwetschge.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_baden.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_beissen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_beten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_betteln.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_binden.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_bluten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_bohren.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_bruellen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_buecken.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_buegeln.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_faellen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_falten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_fangen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_filmen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_fuellen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_giessen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_graben.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_heben.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_hoeren.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_jagen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_joggen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_klopfen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_kneten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_kratzen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_kuessen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_lachen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_landen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_leimen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_loeten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_naehen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_pfluecken.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_putzen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_rauchen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_reiten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_riechen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_rutschen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_saegen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_salzen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_schaelen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_schenken.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_schimpfen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_schluepfen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_schminken.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_schneiden.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_schreien.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_schwimmen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_schwitzen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_segeln.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_singen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_springen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_stehlen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_stempeln.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_stossen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_streicheln.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_streichen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_streiten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_surfen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_tanzen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_tauchen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_taufen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_turnen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_waschen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_wecken.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_weinen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_zahlen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_zeichnen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_birne.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_bluse.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_bohrer.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_bueffel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_buerste.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_dackel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_ente.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_erbse.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_esel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_eule.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_fenchel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_gabel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_glocke.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_gurke.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_hammer.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_hamster.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_hocker.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_jacke.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_joghurt.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_kaefer.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_kaktus.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_kirsche.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_kiste.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_kiwi.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_knoblauch.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_lama.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_locher.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_loeffel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_mantel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_moewe.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_muecke.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_muschel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_nadel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_palme.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_pfirsich.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_pflaster.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_pudel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_ratte.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_rose.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_ruder.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_saege.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_sauce.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_schaufel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_schinken.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_schlitten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_schraube.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_seife.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_sessel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_sofa.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_spargel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_spinne.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_spritze.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_stiefel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_suppe.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_tanne.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_tasse.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_tiger.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_torte.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_trichter.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_tulpe.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_vase.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_wecker.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_wespe.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_wuerfel.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_zebra.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_objekt_zwetschge.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_baden.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_beissen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_beten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_betteln.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_binden.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_bluten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_bohren.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_bruellen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_buecken.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_buegeln.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_faellen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_falten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_fangen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_filmen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_fuellen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_giessen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_graben.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_heben.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_hoeren.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_jagen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_joggen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_klopfen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_kneten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_kratzen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_kuessen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_lachen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_landen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_leimen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_loeten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_naehen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_pfluecken.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_putzen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_rauchen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_reiten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_riechen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_rutschen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_saegen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_salzen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_schaelen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_schenken.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_schimpfen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_schluepfen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_schminken.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_schneiden.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_schreien.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_schwimmen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_schwitzen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_segeln.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_singen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_springen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_stehlen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_stempeln.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_stossen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_streicheln.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_streichen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_streiten.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_surfen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_tanzen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_tauchen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_taufen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_turnen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_waschen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_wecken.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_weinen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_zahlen.png'),
  array('signature' => 'eInclusion_Bilddatenset_DEUTSCH_imageset_eInclusion_fhnw_deutsch_PNG_taetigkeit_zeichnen.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_argue.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_baptise.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_bath.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_beg.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_bend_down.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_bite.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_bleed.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_catch.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_clean.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_cry.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_cut.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_dance.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_dig.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_dive.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_do_gymnastics.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_draw.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_drill.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_fell.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_fill.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_film.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_fold.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_glue.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_hatch.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_hunt.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_iron.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_jog.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_jump.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_kiss.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_knead.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_knock.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_landen.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_laugh.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_lift.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_listen.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_make_a_present.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_make_up.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_paint.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_pay.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_peel.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_pick.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_pour.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_pray.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_push.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_rant.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_ride.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_roar.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_sail.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_salt.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_saw.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_scratch.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_sew.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_shout.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_sing.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_slide.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_smell.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_smoke.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_solder.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_stamp.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_steal.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_stroke.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_surf.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_sweat.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_swim.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_tie.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_wake_up.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_wash.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_alarm_clock.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_armchair.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_asparagus.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_beetle.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_bell.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_blouse.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_boot.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_box.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_brush.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_buffalo.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_cactus.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_cake.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_cherry.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_coat.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_cucumber.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_cup.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_dachshund.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_dice.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_donkey.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_drill.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_duck.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_fennel.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_fir.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_fork.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_funnel.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_garlic.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_ham.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_hammer.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_hamster.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_jacket.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_kiwi.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_lama.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_mosquito.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_needle.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_oar.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_owl.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_palm_tree.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_pea.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_peach.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_pear.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_plaster.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_poodle.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_prune.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_punch.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_rat.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_rose.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_sauce.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_saw.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_screw.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_seagull.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_shell.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_shovel.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_sled.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_soap.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_sofa.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_soup.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_spider.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_spoon.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_stool.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_syringe.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_tiger.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_tulip.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_vase.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_vasp.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_yoghurt.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_Objects_object_zebra.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_001_object_alarm_clock.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_002_object_armchair.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_003_object_asparagus.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_004_object_beetle.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_005_object_bell.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_006_object_blouse.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_007_object_boot.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_008_object_box.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_009_object_brush.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_010_object_buffalo.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_011_object_cactus.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_012_object_cake.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_013_object_cherry.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_014_object_coat.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_015_object_cucumber.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_016_object_cup.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_017_object_dachshund.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_018_object_dice.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_019_object_donkey.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_020_object_drill.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_021_object_duck.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_022_object_fennel.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_023_object_fir.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_024_object_fork.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_025_object_funnel.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_026_object_garlic.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_027_object_ham.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_028_object_hammer.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_029_object_hamster.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_030_object_jacket.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_031_object_kiwi.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_032_object_lama.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_033_object_mosquito.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_034_object_needle.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_035_object_oar.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_036_object_owl.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_037_object_palm_tree.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_038_object_pea.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_039_object_peach.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_040_object_pear.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_041_object_plaster.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_042_object_poodle.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_043_object_prune.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_044_object_punch.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_045_object_rat.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_046_object_rose.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_047_object_sauce.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_048_object_saw.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_049_object_screw.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_050_object_seagull.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_051_object_shell.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_052_object_shovel.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_053_object_sled.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_054_object_soap.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_055_object_sofa.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_056_object_soup.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_057_object_spider.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_058_object_spoon.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_059_object_stool.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_060_object_syringe.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_061_object_tiger.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_062_object_tulip.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_063_object_vase.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_064_object_vasp.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_065_object_yoghurt.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_066_object_zebra.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_067_activity_argue.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_068_activity_baptise.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_069_activity_bath.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_070_activity_beg.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_071_activity_bend_down.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_072_activity_bite.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_073_activity_bleed.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_074_activity_catch.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_075_activity_clean.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_076_activity_cry.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_077_activity_cut.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_078_activity_dance.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_079_activity_dig.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_080_activity_dive.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_081_activity_do_gymnastics.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_082_activity_draw.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_083_activity_drill.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_084_activity_fell.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_085_activity_fill.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_086_activity_film.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_087_activity_fold.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_088_activity_glue.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_089_activity_hatch.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_090_activity_hunt.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_091_activity_iron.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_092_activity_jog.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_093_activity_jump.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_094_activity_kiss.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_095_activity_knead.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_096_activity_knock.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_097_activity_land.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_098_activity_laugh.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_099_activity_lift.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_100_activity_listen.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_101_activity_make_a_present.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_102_activity_make_up.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_103_activity_paint.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_104_activity_pay.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_105_activity_peel.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_106_activity_pick.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_107_activity_pour.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_108_activity_pray.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_109_activity_push.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_110_activity_rant.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_111_activity_ride.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_112_activity_roar.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_113_activity_sail.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_114_activity_salt.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_115_activity_saw.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_116_activity_scratch.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_117_activity_sew.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_118_activity_shout.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_119_activity_sing.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_120_activity_slide.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_121_activity_smell.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_122_activity_smoke.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_123_activity_solder.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_124_activity_stamp.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_125_activity_steal.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_126_activity_stroke.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_127_activity_surf.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_128_activity_sweat.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_129_activity_swim.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_130_activity_tie.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_131_activity_wake_up.png'),
  array('signature' => 'eInclusion_Bilddatenset_ENGLISH_imageset_eInclusion_fhnw_english_PNG_132_activity_wash.png')
);

$english = 'eInclusion_Bilddatenset_ENGLISH';
$german = 'eInclusion_Bilddatenset_DEUTSCH';

$objekte = 'eInclusion_Bilddatenset_DEUTSCH_Objekte_objekt_';
$objects = 'eInclusion_Bilddatenset_ENGLISH_Objects_object_';

$taetigkeiten = 'eInclusion_Bilddatenset_DEUTSCH_Taetigkeiten_taetigkeit_';
$activities = 'eInclusion_Bilddatenset_ENGLISH_Activities_activity_';

$lang = @$_REQUEST['lang'];
$type = @$_REQUEST['type'];

$sub = "";
switch( $lang ) {
	case 'de': 
		switch( $type ) {
			case 'object':
			$sub = $objekte;
			break;
			case 'activity':
			$sub = $taetigkeiten;
			break;
		}
		break;
}

switch( $lang ) {
	case 'en': 
		switch( $type ) {
			case 'object':
			$sub = $objects;
			break;
			case 'activity':
			$sub = $activities;
			break;
		}
		break;
}

?><html>
<head>
	<title>eInclusion</title>
</head>
<body>
<h1>eInclusion</h1>
<?php
if( $sub == '' ) {
	?>
	<h2>Deutsch</h2>
	<ul>
	   <li><a href="?lang=de&type=object">Objekte</a></li>
	   <li><a href="?lang=de&type=activity">Tätigkeiten</a></li>
	</ul>
	<h2>English</h2>
	<ul>
	   <li><a href="?lang=en&type=object">Objects</a></li>
	   <li><a href="?lang=en&type=activity">Activities</a></li>
	</ul>
	<?php
} else {
	$len = strlen($sub);
	echo "<table border=0>\n";
	$cols = 5;
	$col = 0;
	foreach($fullcachewithurl as $val) {
		$signature = $val['signature'];
		if( strncmp($signature, $sub, $len ) != 0 ) continue;
		
		$name = '';
		if( preg_match( "/{$sub}(.+)\.png/", $signature, $matches )) {
			$name = $matches[1];
		}
		
		if( $col % $cols == 0 ) {
			echo "<tr>\n";
		}
		echo "<td style=\"text-align: center;\">";
		echo "<a href=\"https://ba14ns21403-sec1.fhnw.ch/mediasrv/einclusion/{$signature}/resize/size1920x1080\" target=\"_blank\">";
		echo "<img src=\"https://ba14ns21403-sec1.fhnw.ch/mediasrv/einclusion/{$signature}/resize/size250x250\">";
		echo "</a><br />\n";
		echo "{$name}\n";
		echo "</td>\n";
		if( $col % $cols == $cols-1	) {
			echo "</tr>\n";
		}
		$col++;
	}
	echo "</table>";
}
?>
</body>
</html>
